// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GhczAykgRHm4Rhex0yCiOBewaKqm9yo',
    appId: '1:1072592651262:web:c9f1a5927123bd49a176af',
    messagingSenderId: '1072592651262',
    projectId: 'minimal-social-app-674db',
    authDomain: 'minimal-social-app-674db.firebaseapp.com',
    storageBucket: 'minimal-social-app-674db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFFz52iCc7Y4Cs8T7gK2zy3kd6uSxwJE',
    appId: '1:1072592651262:android:8e6b9045e4a4e998a176af',
    messagingSenderId: '1072592651262',
    projectId: 'minimal-social-app-674db',
    storageBucket: 'minimal-social-app-674db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcSoGmLbvostucpUmM4ogNDBuUp4KgAA',
    appId: '1:1072592651262:ios:40337e9e2e3d96b6a176af',
    messagingSenderId: '1072592651262',
    projectId: 'minimal-social-app-674db',
    storageBucket: 'minimal-social-app-674db.firebasestorage.app',
    iosBundleId: 'com.example.socialMinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVcSoGmLbvostucpUmM4ogNDBuUp4KgAA',
    appId: '1:1072592651262:ios:40337e9e2e3d96b6a176af',
    messagingSenderId: '1072592651262',
    projectId: 'minimal-social-app-674db',
    storageBucket: 'minimal-social-app-674db.firebasestorage.app',
    iosBundleId: 'com.example.socialMinApp',
  );
}
