// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCte1pEsmiWtg9Hs3vayHOqaxI_6VZXX9o',
    appId: '1:496436932967:web:d885cbc9ecd73b2bb37fc2',
    messagingSenderId: '496436932967',
    projectId: 'crud-tutorial-c3aa0',
    authDomain: 'crud-tutorial-c3aa0.firebaseapp.com',
    storageBucket: 'crud-tutorial-c3aa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_H_5ar-fH41aPoNQxadrwW7GSwdCIqtI',
    appId: '1:496436932967:android:33464410191ac037b37fc2',
    messagingSenderId: '496436932967',
    projectId: 'crud-tutorial-c3aa0',
    storageBucket: 'crud-tutorial-c3aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgF5IuYt_NnThnEDrQi6ID2ajmFCWtGlI',
    appId: '1:496436932967:ios:56a2e848eb2bf6a2b37fc2',
    messagingSenderId: '496436932967',
    projectId: 'crud-tutorial-c3aa0',
    storageBucket: 'crud-tutorial-c3aa0.firebasestorage.app',
    iosBundleId: 'com.example.onlineDbCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgF5IuYt_NnThnEDrQi6ID2ajmFCWtGlI',
    appId: '1:496436932967:ios:56a2e848eb2bf6a2b37fc2',
    messagingSenderId: '496436932967',
    projectId: 'crud-tutorial-c3aa0',
    storageBucket: 'crud-tutorial-c3aa0.firebasestorage.app',
    iosBundleId: 'com.example.onlineDbCrud',
  );
}
