// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUXG8acImYaFuHKHXyVuaQAZLFGKt6Go',
    appId: '1:20302548148:web:ba5eaa9a878934e3c4dbe1',
    messagingSenderId: '20302548148',
    projectId: 'auth-app-dcf68',
    authDomain: 'auth-app-dcf68.firebaseapp.com',
    storageBucket: 'auth-app-dcf68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9MuDTiHXzjczVlqn3Z4aLWo-76Yuvz0',
    appId: '1:20302548148:android:f6e3fd9d3aadd4dec4dbe1',
    messagingSenderId: '20302548148',
    projectId: 'auth-app-dcf68',
    storageBucket: 'auth-app-dcf68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVVqQoExjYD-SojENWJubtTqavAEQDkg',
    appId: '1:20302548148:ios:0ce61ad81e6203dfc4dbe1',
    messagingSenderId: '20302548148',
    projectId: 'auth-app-dcf68',
    storageBucket: 'auth-app-dcf68.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJVVqQoExjYD-SojENWJubtTqavAEQDkg',
    appId: '1:20302548148:ios:0ce61ad81e6203dfc4dbe1',
    messagingSenderId: '20302548148',
    projectId: 'auth-app-dcf68',
    storageBucket: 'auth-app-dcf68.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );
}
