// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfDj-4lJBACtVLlwtFHnpW5vHqivQ5ch0',
    appId: '1:79139024918:web:e38b4755237f0ae3db4537',
    messagingSenderId: '79139024918',
    projectId: 'push-noti-app-63b09',
    authDomain: 'push-noti-app-63b09.firebaseapp.com',
    storageBucket: 'push-noti-app-63b09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-eKG1zkXrr6inxAjR4srghbFCc3efAw',
    appId: '1:79139024918:android:6142bda2900f076adb4537',
    messagingSenderId: '79139024918',
    projectId: 'push-noti-app-63b09',
    storageBucket: 'push-noti-app-63b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkby68gXkNfZoPHHB7XQQyp8hSedo-VM',
    appId: '1:79139024918:ios:d0dbae86fbe1c114db4537',
    messagingSenderId: '79139024918',
    projectId: 'push-noti-app-63b09',
    storageBucket: 'push-noti-app-63b09.firebasestorage.app',
    iosBundleId: 'com.example.pushNotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkby68gXkNfZoPHHB7XQQyp8hSedo-VM',
    appId: '1:79139024918:ios:d0dbae86fbe1c114db4537',
    messagingSenderId: '79139024918',
    projectId: 'push-noti-app-63b09',
    storageBucket: 'push-noti-app-63b09.firebasestorage.app',
    iosBundleId: 'com.example.pushNotApp',
  );
}
