// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3z9A8MDJmcAT-YuIrrP3p3iBh-w6AzQQ',
    appId: '1:860606439190:web:bb9cdb7a98954465a1fa37',
    messagingSenderId: '860606439190',
    projectId: 'chat-app-2de34',
    authDomain: 'chat-app-2de34.firebaseapp.com',
    storageBucket: 'chat-app-2de34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKhhUF7ZZ5RqOlTFNZN7tHoT2EgnEePY',
    appId: '1:860606439190:android:cffb6720eaca07baa1fa37',
    messagingSenderId: '860606439190',
    projectId: 'chat-app-2de34',
    storageBucket: 'chat-app-2de34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-bjWpog_pVOMnbtjHxiXGuY9KkOmBfJ4',
    appId: '1:860606439190:ios:0c674275ae339aaaa1fa37',
    messagingSenderId: '860606439190',
    projectId: 'chat-app-2de34',
    storageBucket: 'chat-app-2de34.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-bjWpog_pVOMnbtjHxiXGuY9KkOmBfJ4',
    appId: '1:860606439190:ios:0c674275ae339aaaa1fa37',
    messagingSenderId: '860606439190',
    projectId: 'chat-app-2de34',
    storageBucket: 'chat-app-2de34.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
